### PR TITLE
refactor: make background profile non-nullable

### PR DESCRIPTION
**Pull request by goga-m**
## Summary
Closes https://app.clickup.com/t/86drpp492

Affected flows for testing:

* Create a wallet with an empty profile `pnpm dev:bare`
* Import a wallet with an empty profile `pnpm dev:bare` 
* Change something in settings and see it persisted (e.g change local currency)
* Lock/Unlock extension
* Connect from demo & sign/send/vote
* Change password & see it's persisted by locking/unlocking with the new password.

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
conflicts @goga-m , will give it a test afterwards

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
works good until you remove the wallets and redo the onboarding @goga-m . Then you get into a flow where it skips the password step and afterwards you are stuck with this 
image

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
I think I broke my extension

image

Steps:

- `dev:bare`
- Import wallet with passphrase
- Remove wallet
- Import wallet with passphrase - not prompted for another password

**Review by alexbarnsley — APPROVED** [review]
Ignore my last - saw it was already found and fixed. Looks good :+1:

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
