### PR TITLE
refactor: Ledger address selection dark mode styling 

### PR DESCRIPTION
**Pull request by patricio0312rev**
# [[extension] improve styling in Ledger address selection page](https://app.clickup.com/t/86dt0m3ru)

## Summary

- Dark mode styling for Ledger address selection page has been updated to match the designs.

https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/879e5f59-4611-4316-a15d-26a294d5dad4

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
The hover state should be gray-700. 

Design
image


Implementation
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
The selected state doesn't look correct.

Design
image


Implementation
image

**Review by alfonsobries — COMMENTED** [review]
Didnt find a specific design but hover color once address is select feels kinda odd, let see what Reetesh has to say about that

https://helloardent.slack.com/archives/C069X9DHWUR/p1710869913458989

Implementation:

image


https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/a0f75f33-841f-40c1-ba84-312ea7fedcb9

**Review by samharperpittam — CHANGES_REQUESTED** [review]
hmmm quite a few issues with this now @patricio0312rev 

image

1. Default styling appears as if everything is being hovered
2. No hover state on each address
3. No selected state

Design

Hover
image

Selected
image

**Review by samharperpittam — APPROVED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
