### PR TITLE
refactor: ledger address import redesign

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Summary

https://app.clickup.com/t/86drmannx

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by alexbarnsley** [comment]
@goga-m the designs you mentioned are for "already imported" records. There is now designs added for the hover state too. I'll fix the conflicts though :oleglala:

**Review by samharperpittam — CHANGES_REQUESTED** [review]
The hover state shouldn't also fill in the checkbox.

Design
image

Implementation
image

**Review by samharperpittam — COMMENTED** [review]
@alexbarnsley 

Can you try importing a Ledger during onboarding, does your password step look like this?

image

**Comment by ItsANameToo** [comment]
@alexbarnsley I refactored it to only remove padding for the list step, as that is the only one that would need special handling in terms of x-padding

**Comment by ItsANameToo** [comment]
for checkbox we'll have a separate card as it will need checking for other pages to ensure it doesn't break other designs when adding a background to it

**Review by samharperpittam — APPROVED** [review]

**Pull request merged**
