### PR TITLE
refactor: show outline on demo link

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Closes https://app.clickup.com/t/86drqvkdg

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Review by alexbarnsley — APPROVED** [review]

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Unable to tab to this on Firefox

**Comment by alfonsobries** [comment]
@samharperpittam ok the issue was because firefox does not allow by default (at least on some browsers) to focus a link element `<a>` what I did was to convert the ExternalLink component into a button that opens a link, should be fine now but means ensuring all links look good (I checked all of them of course)

**Comment by ItsANameToo** [comment]
relevant details: https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox, cc @samharperpittam 

not sure we want to go out of our way to turn regular link elements into buttons though. It's more a client-side issue and for people that will rely on tabbing I'd expect them to have this turned on to make it work 🤔 would rather see the `<a>` elements returned for semantic reasons

**Comment by ItsANameToo** [comment]
small conflict since @alfonsobries

**Comment by alfonsobries** [comment]
@samharperpittam @ItsANameToo ready ✅

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
