### PR TITLE
refactor: ledger actions status message

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Closes https://app.clickup.com/t/86drqv3u7

note: I had to adjust the modal for approval with the ledger for transactions, specifically the table with details is now scrollable since it didn't all fit with the new message. It shouldn't be a problem as the confirmation screen works this way.

Scenario that this PR does not handle (but also does not work on develop):

1. Disconnect the ledger completely.
2. Initiate an action (like signing a message) and advance until the "waiting for connecting" screen.
3. Try to unlock and open the Ark app. In that case, it doesn't seem to detect the connection to the device or any status change. Wasn't able to find a fix for that, but I think we can create a task for research to see if it can be solved.

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When signing a message on this PR with a Ledger, the width of the page isn't correct anymore. See grey lines at the sides of screenshot.

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
The text within the Ledger status message isn't the correct colour.

Design
image


Imp
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
An issue I have with this PR is that if you do the following:
- Connect Ledger to PC
- Unlock device
- But **do not** open the ARK app

You get the following message when performing an action

`Connect and choose your Ledger device in the browser window`

Shouldn't it be asking to open the ARK app at this stage?

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When the user has the ARK app open on their Ledger device and attempts to send a transaction, the message that gets displayed should be 

"Waiting for your signature"

Currently it displays...

"Open the ARK app on your Ledger device"

The above message should only be displayed when the Ledger is connected but the ARK app isn't open on the Ledger device.

**Comment by samharperpittam** [comment]
Just to give a more in-depth explanation of what should happen with this PR, essentially there should be 3 different states that need to get covered within this PR when attempting to perform an action with a Ledger device.

1. **Ledger device not connected**
When a user attempts to send a transaction with a Ledger address when their Ledger device **is not** connected we should display the following message:

"'Connect and choose your Ledger device in the browser window'"

2. **Ledger device is connected but the ARK app isn't open**
When a user attempts to send a transaction with a Ledger address but the ARK app **is not** open on the Ledger device, we should display the following message:

"'Open the ARK app on your Ledger device'"

3. **Ledger device is connected and ARK app is open**
When a user attempts to send a transaction with a Ledger address and they also have the ARK app open, we should display the following message:

"Waiting for your signature"

**Review by samharperpittam — APPROVED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
