### PR TITLE
refactor: ledger states handling

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Closes https://app.clickup.com/t/86drmrhg3

See details on ticket https://app.clickup.com/t/86drmrhg3?comment=90170023067094

## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — COMMENTED** [review]
Given what @alfonsobries has mentioned on the Clickup task, I'd be inclined to change the checklist as the following:

- [ ] Connect your Ledger device and close other apps connected to it.
- [ ] Click Connect and choose your Ledger device in the browser window.
- [ ] Open the ARK app on the Ledger device.

The last point infers that the user unlocks their device anyway to select the ARK app. So maybe that particular state doesn't need to be handled specifically. 

Thoughts?

**Comment by ItsANameToo** [comment]
Maybe last one can be `Unlock and open the ARK app on the Ledger device.` instead so it covers both, but otherwise seem good to me @samharperpittam

**Comment by alfonsobries** [comment]
@ItsANameToo @samharperpittam updated ✅

**Comment by samharperpittam** [comment]
@alfonsobries  - Would you be able to look at a specific scenario for me to see if we can make any improvements.

- Make sure your Ledger doesn't have the ARK app loaded 
- Disconnect Ledger from PC
- `pnpm dev:bare`
- Import Ledger
- Connect Ledger (do not enter pin to unlock)
- Click "Connect" in extension
- Select Ledger in browser
- Once first 2 checkboxes are complete, unlock device and launch ARK app

I seem to get this error in this specific scenario:
image

(the styling of this error sucks and will create a task to fix it)

It feels like the process times out or something, was wondering if it could be improved at all.

**Comment by alfonsobries** [comment]
@samharperpittam @ItsANameToo I can't solve the problem, but one thing I can say is that the same problem exists in develop, just the steps are different:

1. Press continue and wait for the window to select ledger.
2. Connect ledger and unlock (without opening the ark app).
3. It redirects to the steps page.
4. Open the ark app, it will redirect to the select wallets screen with the same error message.

I think it's something with the SDK or ledger SDK, can't really say, maybe it requires its own task to research. I've been on this for many hours by now with no luck.

**Comment by samharperpittam** [comment]
> @samharperpittam @ItsANameToo I can't solve the problem, but one thing I can say is that the same problem exists in develop, just the steps are different:
> 
> 1. Press continue and wait for the window to select ledger.
> 2. Connect ledger and unlock (without opening the ark app).
> 3. It redirects to the steps page.
> 4. Open the ark app, it will redirect to the select wallets screen with the same error message.
> 
> I think it's something with the SDK or ledger SDK, can't really say, maybe it requires its own task to research. I've been on this for many hours by now with no luck.

Thanks for looking into it. I'll create a specific task for it and also see if the same issue exists within Vault too.

**Review by samharperpittam — APPROVED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
