### PR TITLE
refactor: get rid of timeouts

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Closes https://app.clickup.com/t/86drmbr1z and https://app.clickup.com/t/86drm115q

Note: I was unable to test the ledger part because I did not received my ledger replacement yet, so need some help with that part in specific

## What to test?

Ensure the loading screen/temporary success screen appears/dissapears depending on the context and time. For example, when creating a wallet, a "setting up wallet" message should be displayed, followed by a "wallet created" message. That last message should appear for 3 seconds before redirecting to the home page. In some instances, the success message may not display, or the window may close after the action. This behavior isn't new, but the code has been cleaned up. In short the idea is to verify that these screens are still functioning as they use to.

https://github.com/ArdentHQ/arkconnect-extension/assets/17262776/09766504-1f05-4efd-9f84-1d68e991d7e3

_PD: on the video im not validating the mnenmonic, thats a local adjustment for fasting testing ignore that part_
## Checklist

- [ ] I checked that both `pnpm dev` and `pnpm dev:bare` work as intended
- [ ] I checked the basic extension interactions and made sure wallet selection works
- [ ] I checked my UI changes against the design and there are no notable differences, including responsiveness
- [ ] I checked my (code) changes for obvious issues, debug statements and commented code
- [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
- [ ] I added a short description on how to test this PR _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Review by alexbarnsley — COMMENTED** [review]
I can't tell if it's my imagination but vote seems to confirm/approve too quickly :thinking: what's the intended usage for votes, should it wait for confirmation?

**Comment by alfonsobries** [comment]
@alexbarnsley It's fast but not so fast that I don't see a 'Loading' message, I think it's just the time it takes, in the end, it shows a confirmation message so I also assume it was correct. I don't see any problems in the code but I'll see if someone else can check to have another insight

**Comment by alfonsobries** [comment]
will move as ready while we discuss if speed is an issue

**Comment by alfonsobries** [comment]
@alexbarnsley @ItsANameToo added a wait timeout

**Review by alexbarnsley — APPROVED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
